### ISSUE TITLE
Ardour can't open video files

### ISSUE THREAD

**Issue by KristijanZic** [flathub/org.ardour.Ardour#12]
Ardour is missing some dependencies that should have been bundled in order for Ardour to be usable for sound mixing for film.
Those are described here and come in the official package:
https://manual.ardour.org/video-timeline/setup/

The missing deps cause current broken behaviour:
Try to open a video file by going `Session > Open Video...` in the local menu under the window titlebar.

The action will fail and Ardour will complain about missing hardvid dependency like seen in the screenshot below:
![Screenshot from 2020-12-12 01-36-11](https://user-images.githubusercontent.com/10299892/101967074-96197880-3c1a-11eb-8773-9d5de72843d4.png)

Could you please package those with the Ardour in the Flatpak?

System specs:
<details>
<summary>neofetch</summary>
<pre>
OS: Ubuntu 20.04.1 LTS x86_64 
Kernel: 5.4.0-54-generic 
Uptime: 2 hours, 10 mins 
Packages: 1972 (dpkg), 74 (flatpak), 37 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1200, 2560x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen Threadripper 1900X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX Vega 56/64 
Memory: 3926MiB / 15930MiB 
</pre>
</details>

Thanks for the package!

**Comment by hfiguiere** [comment]
This will require PR #14 at first, and then PR #15
