### ISSUE TITLE
Add Surge Synthesizer to FlatHub.

### ISSUE THREAD

**Issue by zarp-dev** [flathub/org.ardour.Ardour#13]
Hi!
Thank you for maintaining this wonderful DAW and some of plugins for it!
Can you upload Surge Synthesizer to FlatHub?
Surge is an amazing synth! It has a lot of power! And of course it's floss. 
There is no LV2 version yet, but VST3 is good enough and is supported by Ardour since 6.5 version.
![image](https://user-images.githubusercontent.com/65812041/102707006-2190aa80-42a8-11eb-94f8-789c03d93c44.png)

**Comment by hfiguiere** [comment]
It's already on Flathub.

`flatpak install org.freedesktop.LinuxAudio.Plugins.Surge//20.08`

**Comment by hfiguiere** [comment]
There is indeed a discovery problem, but not much I can do here.
