### ISSUE TITLE
Jack doesn't work due to missing(?) jack.conf/client.conf

### ISSUE THREAD

**Issue by ingobecker** [flathub/org.ardour.Ardour#21]
I'm using fedora 33 and the latest version `4de76372a0f96f8e1aff7f45265f4dd79e3737705386fec0aa43bdf9f8479034` of the flatpak of ardour. I followed the description in the [readme](https://github.com/flathub/org.ardour.Ardour#jack-audio-support) (uninstalled the local version of `jack` and installed `pipewire-jack-audio-connection-kit`). Once i start ardour and select `jack` as the audio system from the shown audio/midi setup dialog confirming my selection by clicking start fails with the error `Could not reconnect to Audio/MIDI engine`. The terminal output looks like this:

```
JACK command line will be: /app/bin/jackd -t 200 -p 2048 -R -T -d alsa -n 2 -r 44100 -p 64 -d hw:PCH,0 -X raw
[W][000006763.443007][context.c:224 pw_context_new()] context 0x559e8a07a800: can't load config jack.conf: No such file or directory. Using client.conf fallback
[E][000006763.443140][context.c:232 pw_context_new()] context 0x559e8a07a800: can't load client.conf config: No such file or directory
```

Choosing pulse works as expected.

**Comment by hfiguiere** [comment]
it's a known bug (regression) in the freedesktop-sdk, we hope an update will be available soon.

With pulse you don't get MIDI support.

**Comment by hfiguiere** [comment]
This is the issue tracking it
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1223

**Comment by ingobecker** [comment]
thanks for the very fast reply and the link. i will then wait for the runtime to be updated.

**Comment by hfiguiere** [comment]
The runtime was updated and it works here.

Let me know if you still have issues.

**Comment by ingobecker** [comment]
Works for me as well.
