### ISSUE TITLE
I think export is broken

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.ardour.Ardour#24]
I'm new to Ardour but having searched for my problem and checked YouTube videos I can't see that I'm doing anything wrong.

When exporting audio it always seems to hang Ardour. The export progress bar may move from left-to-right as a single colour or, rarely, as a two colour object. Then nothing happens.

Looking in the export directory of the session I see a file representing the export e.g. session.wav but it's only a few hundred bytes in size. There is an accompanying file named with uppercase letters and numbers which might be the export content.

I've left Ardour sufficiently long enough to finish the export but I have to stop the export and force-quit Ardour.

UPDATE: This appears to be a pipewire/jack issue. If I attempt the same using the ALSA backend the export works. I did have to enable realtime priority for ALSA in an /etc/security/limits.d/... file though.

I would appreciate feedback from anyone who has successfully used Ardour-6.7.0 in this flatpak packaging to determine whether it does work or not.

OS: fedora SilverBlue
Audio engine: pipewire-0.3.28 w/ pipewire-jack-audio-connection-kit

**Comment by hfiguiere** [comment]
pipewire jack still has issue, and it would be nice to get the output of the console from ardour as there are probably messages giving a bit more information. I use ALSA usually.

**Comment by neildarlow** [comment]
Hi @hfiguiere

I ran ardour6 from a shell prompt in the flatpak and there's absolutely no output during the export process. Checking the journal of the host gives no clues either.

It appears that the export activity just hangs. If you're lucky, you can cancel the export otherwise you have to perform a force quit.

**Comment by neildarlow** [comment]
I chatted with Wim Tayams (pipewire author) on IRC and his opinion is this isn't a pipewire issue. The ALSA Broken Pipe message in that log isn't relevant.

I've seen a couple of Discourse posts that audio export is problematic with JACK/pipewire on Ardour since 6.6. It worked OK with 6.5 apparently.

**Comment by edgimar** [comment]
Ardour has a log that can be accessed from within the application (small red circle button in upper right corner).  I also can't export with the flatpak version (tried both `CD (Red Book)` and `MP3 (standard)` -- some possibly relevant parts of the ardour log for me are:
```
2021-06-14T21:02:51 [INFO]: Searching for export formats in /home/user/.var/app/org.ardour.Ardour/config/ardour6/export:/app/share/ardour6/export
2021-06-14T21:07:17 [INFO]: Searching for export formats in /home/user/.var/app/org.ardour.Ardour/config/ardour6/export:/app/share/ardour6/export
2021-06-14T21:07:21 [ERROR]: XML error: failed to load external entity "/home/user/.var/app/org.ardour.Ardour/config/ardour6/export/CD (Red Book).format"
2021-06-14T21:08:14 [INFO]: Encode command: { /app/bin/ffmpeg_harvid -f f32le -acodec pcm_f32le -ac 2 -ar 48000 -i pipe:0 -y -q:a 2 -metadata comment=Created with Ardour /home/user/ardour_sessions/test/export/test_Loop.mp3 }
```
I'm using pipewire's JACK interface, and recording works fine with it.  It's only the exporting of (even very short) recorded tracks that is having a problem (just waits at "Exporting ..." without the export ever finishing).

**Comment by neildarlow** [comment]
@edgimar Are you enabling Realtime in the export dialog?

I believe what you're seeing is due to the mis-match between the pipewire library versions in the flatpak and your OS. There is also an issue with MP3 encoding which I've put into another issue.

**Comment by edgimar** [comment]
I did not enable realtime when exporting, and was only exporting the master
bus.

**Comment by neildarlow** [comment]
@edgimar

For my use case (podcast production) I'm exporting in 32-bit floating-point WAV format and I convert to MP3 using SoundConverter. You should be able to do this directly from Ardour but, until things are fixed, this is a working solution and it seems to work with or without realtime export.

**Comment by Yajo** [comment]
> I'm exporting in 32-bit floating-point WAV format

Could you post a screenshot? It doesn't work for me but I don't know if maybe I'm using wrong configuration.

**Comment by neildarlow** [comment]
@Yajo,

Sure, here's the export format and channel configuration.

![podcast-format](https://user-images.githubusercontent.com/6245505/122467739-cae3ff00-cfb2-11eb-823c-5ce86964bbbf.png)
![podcast-channels](https://user-images.githubusercontent.com/6245505/122467757-cfa8b300-cfb2-11eb-8cd9-780113ccf22d.png)
