### ISSUE TITLE
Can't export to MP3

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.ardour.Ardour#26]
Hi,

I'm using Ardour 6.7.0 with ALSA as the audio engine. I can record and playback sound without issue.

When attempting to export to MP3 (using the Standard MP3, session rate format) the export fails with the following in the log:

2021-06-09T10:22:52 [INFO]: Encode command: { /app/bin/ffmpeg_harvid -f f32le -acodec pcm_f32le -ac 2 -ar 48000 -i pipe:0 -y -q:a 2 -metadata comment=Created with Ardour /var/home/neil/Audio/test/export/session.mp3 }
2021-06-09T10:22:52 [ERROR]: Export ended unexpectedly: Exception thrown by AudioGrapher::CmdPipeWriter<float>: Target encoder process is not running

**Comment by neildarlow** [comment]
I did some digging on this and, checking the capabilities of ffmpeg_harvid, it seems to have muxing and demuxing support for MP3 but I don't see any evidence of MP3 encoding support. Here's some output (ffmpeg copyright and library versions omitted:

[📦 org.ardour.Ardour ~]$ ffmpeg_harvid -decoders |grep -i mp3
 A....D mp3float             MP3 (MPEG audio layer 3) (codec mp3)
 A....D mp3                  MP3 (MPEG audio layer 3)
 A....D mp3adufloat          ADU (Application Data Unit) MP3 (MPEG audio layer 3) (codec mp3adu)
 A....D mp3adu               ADU (Application Data Unit) MP3 (MPEG audio layer 3)
 A....D mp3on4float          MP3onMP4 (codec mp3on4)
 A....D mp3on4               MP3onMP4

[📦 org.ardour.Ardour ~]$ ffmpeg_harvid -encoders |grep -i mp3

[📦 org.ardour.Ardour ~]$ ffmpeg_harvid -muxers |grep -i mp3
  E mp3             MP3 (MPEG audio layer 3)

Am I missing something here or is the lack of MP3 encoder a likely cause of the failure?

**Comment by srahman53171618** [comment]
Just wanted to add, same issue here

**Comment by hfiguiere** [comment]
Sorry this stuck under my radar. It shoud be fixed now.

**Comment by srahman53171618** [comment]
Thank you so much.
