### ISSUE TITLE
Add access to XDG config directory

### ISSUE THREAD

**Issue by afranke** [flathub/org.ardour.Ardour#30]
Please add `--filesystem=xdg-config` to the manifest. Ardour can’t access the files I have put in `.config/ardour6/patchfiles` currently.

**Comment by hfiguiere** [comment]
The config directory inside the sandbox is `~/.var/app/org.ardour.Ardour/config/ardour6`

Given that Ardour has access to the whole `$HOME` what you request would do nothing.

**Comment by hfiguiere** [comment]
ok so with clarfications, giving the permission `--filesystem=xdg-config/ardour6` would use the "host" (the one in `~/.config`) configuration inside the flatpak sandbox, but doing so right now would break current users setup.
