### ISSUE TITLE
LinuxAudio plugins from Flathub not visible to Ardour installation

### ISSUE THREAD

**Issue by AnonHedge** [flathub/org.ardour.Ardour#40]
Good day,

Distro: Attempted on Fedora 36 Kinoite/Silverblue, Fedora 35 Workstation

I've been trying to understand how to load up plugins with the `org.freedesktop.LinuxAudio.Plugins` prefix on the Ardour flatpak and so far have been unsuccessful. So far I have attempted:
1) Installing the Helm and Calf plugins from Flathub - versions 21.08 since it appears 20.08 is deprecated.
2) Installing Ardour either directly from Ardour, through rpm-ostree, a Fedora toolbox, and the Flatpak version.
3) Attempted to give the flatpak special privileges with flatseal and include the /var/ directory, since this is where the runtime is located for the plugins. This was unsuccessful, though not terribly surprisingly since I couldn't actually reach the runtime folder. I suspect there's a good reason why Flatpaks can't access their runtime environment but I was getting a bit desperate by this point and wanted to see if it stuck or not.

From what I can tell folks generally can install the flatpaks and they "just work", though I have stumbled into some reference that perhaps this process [isn't that simple](https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension/issues/5#issuecomment-986320089). Truthfully at this point I'm a bit lost and could use some assistance figuring out how this is supposed to work. It could be a problem specific to Fedora, though I am starting to doubt that since I saw the same behaviors on Kinoite and Workstation, so I really don't have any other ideas for what could have caused this...

Thank you for your time!

**Comment by hfiguiere** [comment]
> 2\. nstalling Ardour either directly from Ardour, through rpm-ostree, a Fedora toolbox, and the Flatpak version.

This is only the flathub version that is the subject here, and the flathub distributed plugins will not work with anything else. 

Not with the official Ardour builds, nor anything from Fedora.

If you can't see the plugins, then you are likely running the wrong version (ie not the one from Flathub).

Also Ardour needs to see the plugins see the Plugin Manager.

**Comment by AnonHedge** [comment]
Ahhhh..... Yes that appears to have been the problem, I tried every combination I could think of for the plugins but had assumed the Fedora and Flathub distributed versions of Ardour were both capable of using those plugins. Thank you for pointing that out, it looks like Ardour is discovering the plugins as expected now!

If you'd like I'd be happy to post a pull request with some summarized gotchas added into the readme from this experience. If you think this issue is sufficient documentation, then feel free to close it.

**Comment by hfiguiere** [comment]
this README is not for users.

As for the confusion, I'd redirect the grief with with Fedora. They could actually make that work, or simply abstain and use Flathub instead of the default filtered view.
