### ISSUE TITLE
Sound setup messes with KDE devices

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.ardour.Ardour#59]
First of all, great that this even works. Crazy how much access apps have on that.

KDE shows a mute popup once the latency tests start. But apart from that, nothing shows. Sound devices are duplicated afterwards, and a reboot is needed to fix this.

Would be great if you could use some different method of muting other devices and gaining full sound access, because this breaks things currently.

```
Specified App:
org.ardour.Ardour	7.5.0	stable	flathub

--- Software ---
OS: Fedora Linux 38.20230808.0 (Kinoite)
KDE Plasma: 5.27.6
KDE Frameworks: 5.108.0
Qt: 5.15.10
Kernel: 6.4.7-200.fc38.x86_64
Compositor: wayland

--- Hardware ---
CPU: AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx
RAM: 13.5 GB
GPU: AMD Radeon Vega 8 Graphics
Video memory: 2048MB

```

**Comment by hfiguiere** [comment]
I have no idea what you are talking about.

**Comment by firefoxlover** [comment]
When starting in general Ardour hijacks the complete sound output of the System and mutes all other apps. Its pretty crazy, nice I guess but not so well received by the system, in that the apps dont automatically unmute again afterwards etc.

**Comment by hfiguiere** [comment]
let me guess: you are using the ALSA backend...

**Comment by firefoxlover** [comment]
uhm yes, I use pipewire and whatnot, and I think that was not an option

**Comment by hfiguiere** [comment]
The ALSA backend get exclusive use of the audio interface. Flatpak or not.

The JACK backend (it connects to Pipewire) doesn't have the problem.

**Comment by firefoxlover** [comment]
thank you. If this is documented somewhere, I close this issue ;D
